version: "3"
services:
  app:
   platform: linux/arm64
   image: $REGISTRY_IMAGE
   restart: always
   env_file: .env.prod
   ports:
     - "127.0.0.1:12372:8080"
   volumes:
     - "./data/keydb:/opt/bastillion/jetty/bastillion/WEB-INF/classes/keydb/"
   healthcheck:
     test: curl -I -L http://localhost:8080/admin || exit 1
     interval: 10s
     timeout: 75s
     retries: 8
